### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ddugovic** [grubbcc/anagrams#1]
Might this code be available under a free software license (to copy, redistribute, and modify)?

EDIT: Now I see in the README... this just didn't show in the sidebar where GitHub normally shows a license:
![image](https://user-images.githubusercontent.com/1834123/154323876-46b52a9a-5b62-4e8b-a72c-f70485294a2a.png)

> Since I have benefited greatly from the advice and code of others, I have made this an open source project. Check out the code over at my GitHub page, and feel free to use what you like in your own work. (Just no redistributing or selling without my permission, of course.)

**Comment by grubbcc** [comment]
Thanks for asking. I went ahead and added the MIT license. I'm inclined to be lenient if people to reuse and learn from my code, but they should provide attribution if they want to fork the project in large part or as a whole. I am now working in conjunction with the team from woogles.io, so I will run the issue by them to make sure there isn't any conflict.
